---
hide.anonymous: FALSE
title: |
  | Human Trafficking Survey Results Report
  | • • •
  | Organizations in Indonesia
  | • • •
author: "Judith Kelley"
date: "`r format(Sys.time(), '%B %e, %Y')`"
mainfont: DejaVu Sans
fontsize: 10pt
output:
  pdf_document:
    includes:
      in_header: ../TeX/top_stuff_individual.tex
    latex_engine: xelatex
    toc: yes
    toc_depth: 1
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
# Set the working directory one level back
library(knitr)
opts_knit$set(root.dir = normalizePath('../'))
opts_chunk$set(cache=FALSE)

library(pander)
panderOptions('table.split.table', Inf)
# panderOptions('knitr.auto.asis', FALSE)  # Someday

library(tidyr)
library(magrittr)

load("../Data/responses.RData")

# Load plotting helper functions
source("../R/summary_functions.R", chdir=TRUE)


output.organization <- function(country.row.id) {
  org.data <- orgs.in.country %>% slice(country.row.id)
  
  org.id <- org.data$survey.id
  
  num.countries <- filter(responses.countries, survey.id == org.id) %>% nrow()
  
  org.name <- org.data$Q1.2
  survey.date <- format(org.data$end.time, format="%B %d, %Y")
  
  answer.summary <- function(df, cols, labs, other.response) {
    cols.to.select <- which(colnames(df) %in% cols)
    
    df.clean <- df %>%
      select(cols.to.select) %>%
      set_colnames(labs) %>%
      gather(question, value) %>%
      filter(!is.na(value)) %>%
      mutate(question = as.character(question)) %>%
      select(question)
    
    if(!is.na(other.response)) {
      other <- df %>% select(which(colnames(df) %in% other.response)) %>% slice(1)
      
      if(!is.na(other[,1])) {
        reg.responses <- df.clean$question[df.clean$question != "Other"]
        other.responses <- paste("Other:", other[,1])
        all.responses <- paste(c(reg.responses, other.responses), collapse="; ")
      } else {
        all.responses <- paste(df.clean$question, collapse="; ")
      } 
    } else {
      all.responses <- paste(df.clean$question, collapse="; ")
    }
    
    all.responses
  }
  
  first.questions <- c("Q1.3: Would you like your organization to remain anonymous in this study's reports?", 
                       "Q1.4: Where is your organization's main office?", 
                       "Q1.5: In how many countries has your organization done most of its advocacy work over the past 10 years?", 
                       "Q2.1: About what percent of your organization's time and resources are spent on fighting against trafficking or helping victims of trafficking?", 
                       "Q2.2: Which human trafficking issues is your organization most involved with?", "Q2.3: Which kinds of victims is your organization most involved with?", 
                       "Q2.4: Which efforts does your organization focus on most?", 
                       "Q2.5: The US State Department issues an annual Trafficking in Persons (TIP) report. Have you ever heard of this annual report?", 
                       "Q2.6: In Fall 2013 an NGO named WalkFree published a \"Human Trafficking Index\" that rated countries on how many trafficking victims they have. Have you heard of this index?")
  
  
  first.answers <- org.data %>%
    mutate(Q1.3 = as.character(Q1.3), home.country = as.character(home.country), 
           Q1.5.factor = as.character(Q1.5.factor), 
           Q2.5 = as.character(Q2.5), Q2.6 = as.character(Q2.6)) %>%
    mutate(Q2.2 = answer.summary(., c("Q2.2_1", "Q2.2_2", "Q2.2_3", "Q2.2_4"), 
                                 c("Organ trafficking", "Sex trafficking", 
                                   "Labor trafficking", "Other"), 
                                 "Q2.2_4_TEXT")) %>%
    mutate(Q2.3 = answer.summary(., c("Q2.3_1", "Q2.3_2", "Q2.3_3"), 
                                 c("Children", "Adults", "Other"), 
                                 "Q2.3_3_TEXT")) %>%
    mutate(Q2.4 = answer.summary(., c("Q2.4_1", "Q2.4_2", "Q2.4_3", "Q2.4_4", "Q2.4_5"), 
                                 c("Prevention and education", 
                                   "Prosecutions and legal issues", 
                                   "Victim protection", "Victim assistance", "Other"), 
                                 "Q2.4_5_TEXT")) %>%
    select(Q1.3, home.country, Q1.5.factor, 
           Q2.1, Q2.2, Q2.3, Q2.4, Q2.5, Q2.6) %>%
    set_colnames(first.questions)
  
  
  last.questions <- c("Q4.1: Do you have any additional comments?",
                      "Q4.2: May we contact you for any follow up questions?",
                      "Q4.3: Would you like to be notified of the results of this survey once it is completed?",
                      "Q4.4: E-mail address",
                      "Q4.5: Phone")
  
  last.answers <- org.data %>%
    mutate(Q4.2 = as.character(Q4.2), Q4.3 = as.character(Q4.3)) %>%
    select(Q4.1, Q4.2, Q4.3, Q4.4, Q4.5) %>%
    set_colnames(last.questions)
  
  
  output.country <- function(row.id) {
    actual.countries <- responses.countries %>%
      filter(survey.id == org.id) %>% slice(row.id)
    
    country.name <- as.character(actual.countries$work.country)
    
    country.questions <- c("Q3.3: How much does your organization know about human trafficking policy in X?", 
                           "Q3.4: How often does your organization work directly with the government of X?", 
                           "Q3.5: In X, which of these institutions have been active in fighting human trafficking over the last 10–15 years?", 
                           "Q3.6: Which embassies or foreign governments have been active in fighting human trafficking in X?", 
                           "Q3.7: Which of these embassies or foreign governments have been the most active?", 
                           "Q3.8: Over the last 10–15 years, has the United States or its embassy been active in the fight against human trafficking in X?", 
                           "Q3.9: Has the United States or its embassy been involved in any of the following activities in X?", 
                           "Q3.10: Please explain how the United States asked the government to pass or amend anti-trafficking laws in X:", 
                           "Q3.11: Please explain how the United States convened conferences or workshops on trafficking in X:", 
                           "Q3.12: Please explain how the United States raised awareness about trafficking in X:", 
                           "Q3.13: Please explain how the United States provided resources or funding for anti-trafficking programs in X:", 
                           "Q3.14: Please explain how the United States increased government attention to trafficking in X:", 
                           "Q3.15: Please explain how the United States trained government officials in X:", 
                           "Q3.16: Please explain how the United States contributed to a government action plan in X:", 
                           "Q3.17: Please explain how else the US government has been involved in trafficking issues in X:", 
                           "Q3.18: Over the last 10–15 years, has your organization worked directly with or had direct contact with the US embassy or government on human trafficking issues?", 
                           "Q3.19: Overall, how important a role would you say that the United States or its embassy have played in fighting trafficking in X over the last 10–15 years?", 
                           "Q3.20: In your view, how hard is the government of X working to combat trafficking in persons?", 
                           "Q3.21: Has your organization used the US State Department's Trafficking in Persons (TIP) report to discuss trafficking issues with any of these groups?", 
                           "Q3.22: Which TIP tier rating did X receive this year?", 
                           "Q3.23: Have you ever heard—in public or private—officials in X mention the TIP tier rating?", 
                           "Q3.24: What was their reason for mentioning it?", 
                           "Q3.25: Overall, has the US influence on human trafficking policy in X been positive or negative?",
                           "Q3.26: Would you say that the government of X's efforts to combat trafficking over the past 10–15 years have:", 
                           "Q3.27: Does a member of the government or ruling party of X sit on your board?", 
                           "Q3.28: Is your organization required by law to have a member of the government or ruling party sit on your board?", 
                           "Q3.29: How much is your organization's work restricted by government regulations in X?", 
                           "Q3.30: How is your organization's work restricted by government regulations in X?")
    
    country.nice <- actual.countries %>%
      mutate(Q3.3 = as.character(Q3.3), Q3.4 = as.character(Q3.4),
             Q3.8 = as.character(Q3.8), Q3.19 = as.character(Q3.19), 
             Q3.20 = as.character(Q3.20), Q3.22 = as.character(Q3.22),
             Q3.23 = as.character(Q3.23), Q3.25 = as.character(Q3.25),
             Q3.26 = as.character(Q3.26), Q3.27 = as.character(Q3.27),
             Q3.28 = as.character(Q3.28), Q3.29 = as.character(Q3.29)) %>%
      mutate(Q3.5 = answer.summary(., c("Q3.5_1", "Q3.5_2", "Q3.5_3", "Q3.5_4", "Q3.5_5"), 
                                   c("The national government", "NGOs and civil society",
                                     "Embassies or foreign governments", 
                                     "International organizations", "Other"), 
                                   "Q3.5_5_TEXT")) %>%
      mutate(Q3.9 = answer.summary(., c("Q3.9_1", "Q3.9_2", "Q3.9_3", "Q3.9_4", "Q3.9_5",
                                        "Q3.9_6", "Q3.9_7", "Q3.9_8", "Q3.9_9", "Q3.9_10"), 
                                   c("Asking for legislation", 
                                     "Convening conferences or workshops",
                                     "Raising awareness", 
                                     "Providing resources or funding",
                                     "Increasing government attention", 
                                     "Training government officials",
                                     "Contributing to a government action plan", 
                                     "Other", "Don't know",
                                     "The US has not been involved in trafficking issues"), 
                                   NA)) %>%
      mutate(Q3.18 = answer.summary(., c("Q3.18_1", "Q3.18_2", "Q3.18_3", "Q3.18_4", 
                                         "Q3.18_5", "Q3.18_6"), 
                                    c("Direct contact (meetings)", "Direct cooperation", 
                                      "Our organization received funding", "Other", 
                                      "We have not had any contact or funding from the US",
                                      "Don't know"), 
                                    "Q3.18_4_TEXT")) %>%
      mutate(Q3.21 = answer.summary(., c("Q3.21_1", "Q3.21_2", "Q3.21_3", "Q3.21_4"), 
                                    c("Government of X", "Another government", 
                                      "Other NGOs", "Other"), 
                                    "Q3.21_4_TEXT")) %>%
      select(Q3.3, Q3.4, Q3.5, Q3.6, Q3.7, Q3.8, Q3.9, Q3.10, Q3.11, Q3.12, Q3.13, Q3.14,
             Q3.15, Q3.16, Q3.17, Q3.18, Q3.19, Q3.20, Q3.21, Q3.22, Q3.23, Q3.24, Q3.25,
             Q3.26, Q3.27, Q3.28, Q3.29, Q3.30) %>%
      set_colnames(country.questions)
    
    pandoc.header(country.name, level=2)
    pandoc.table(t(country.nice), justify="left")
  }
  
  pandoc.header(org.name)
  pandoc.p(paste0(c("Survey ID: "), "`", org.id, "`"))
  pandoc.p(paste0(c("Filled out on ", survey.date)))
  pandoc.header("Initial questions", level=2)
  pandoc.table(t(first.answers), justify="left")
  sapply(1:num.countries, FUN=output.country)
  pandoc.header("Final questions", level=2)
  pandoc.table(t(last.answers), justify="left")
}
```


```{r, echo=FALSE, results='asis'}
country.id <- 79
orgs.in.country <- filter(responses.org, Q1.4 == country.id)
num.orgs.in.country <- nrow(orgs.in.country)
# sapply(1:num.orgs.in.country, FUN=output.organization)
for(i in 1:num.orgs.in.country) {
  output.organization(i)
}
```

